/**
 * FlexDash Embedded Dashboard Data
 *
 * This file is generated by the pipeline so the dashboard works when opened
 * as a local file (file:// protocol).
 * Generated: 2026-02-17 14:17:00
 */

/**
 * Convert a value to a disclosure-safe range bucket
 * Used for cells with k < 3 contributors (where ranges are shown).
 */
function getDisclosureRange(valueMW) {
    if (valueMW === 0) return { label: '0 MW', min: 0, max: 0, midpoint: 0 };
    if (valueMW < 10) return { label: '<10 MW', min: 0, max: 10, midpoint: 5 };
    if (valueMW < 50) return { label: '10-50 MW', min: 10, max: 50, midpoint: 30 };
    if (valueMW < 100) return { label: '50-100 MW', min: 50, max: 100, midpoint: 75 };
    if (valueMW < 250) return { label: '100-250 MW', min: 100, max: 250, midpoint: 175 };
    if (valueMW < 500) return { label: '250-500 MW', min: 250, max: 500, midpoint: 375 };
    if (valueMW < 1000) return { label: '0.5-1 GW', min: 500, max: 1000, midpoint: 750 };
    if (valueMW < 2500) return { label: '1-2.5 GW', min: 1000, max: 2500, midpoint: 1750 };
    if (valueMW < 5000) return { label: '2.5-5 GW', min: 2500, max: 5000, midpoint: 3750 };
    if (valueMW < 10000) return { label: '5-10 GW', min: 5000, max: 10000, midpoint: 7500 };
    return { label: '>10 GW', min: 10000, max: 15000, midpoint: 12500 };
}

window.getDisclosureRange = getDisclosureRange;

const DASHBOARD_DATA = {
  "generated_at": "2026-02-17T14:17:00.449001",
  "version": "1.0.0",
  "study_period": "Nov 2024-Feb 2025",
  "is_demo": true,
  "subtitle": "DEMONSTRATION - Synthetic Data",
  "metrics": {
    "total_available_mw": 16300,
    "total_delivered_mw": 0.0,
    "delivery_factor_pct": 0.0,
    "contributor_count": 15,
    "total_available_mw_illustrative": false,
    "total_available_range": null,
    "total_available_range_min": null,
    "total_available_range_max": null,
    "total_delivered_mw_illustrative": true,
    "total_delivered_range": "0 MW",
    "total_delivered_range_min": 0.0,
    "total_delivered_range_max": 0.0,
    "domestic": {
      "available_mw": 0.0,
      "delivered_mw": 0,
      "available_mw_illustrative": true,
      "available_range": "0 MW",
      "available_range_min": 0.0,
      "available_range_max": 0.0
    },
    "ic": {
      "available_mw": 0.0,
      "delivered_mw": 0,
      "available_mw_illustrative": true,
      "available_range": "0 MW",
      "available_range_min": 0.0,
      "available_range_max": 0.0
    }
  },
  "sector_breakdown": [
    {
      "sector": "unknown",
      "capacity_mw": 16300.0,
      "count": 314200,
      "k": 7,
      "k_capacity_mw": 7,
      "k_count": 7,
      "count_range": null,
      "count_range_min": null,
      "count_range_max": null,
      "capacity_mw_illustrative": false,
      "count_illustrative": false
    },
    {
      "sector": "domestic",
      "capacity_mw": null,
      "count": 300000,
      "k": 0,
      "k_capacity_mw": 0,
      "k_count": 3,
      "count_range": "100k-500k",
      "count_range_min": 100000.0,
      "count_range_max": 500000.0,
      "capacity_mw_illustrative": false,
      "count_illustrative": true
    },
    {
      "sector": "ic",
      "capacity_mw": null,
      "count": 7500,
      "k": 0,
      "k_capacity_mw": 0,
      "k_count": 6,
      "count_range": "5k-10k",
      "count_range_min": 5000.0,
      "count_range_max": 10000.0,
      "capacity_mw_illustrative": false,
      "count_illustrative": true
    }
  ],
  "asset_breakdown": [
    {
      "asset_class": "unknown",
      "capacity_mw": 16300.0,
      "count": 314200.0,
      "k": 7,
      "k_capacity_mw": 7,
      "k_count": 7,
      "count_range": null,
      "count_range_min": null,
      "count_range_max": null,
      "capacity_mw_illustrative": false,
      "count_illustrative": false
    },
    {
      "asset_class": "battery_storage",
      "capacity_mw": null,
      "count": 300000.0,
      "k": 0,
      "k_capacity_mw": 0,
      "k_count": 6,
      "count_range": "100k-500k",
      "count_range_min": 100000.0,
      "count_range_max": 500000.0,
      "capacity_mw_illustrative": false,
      "count_illustrative": true
    },
    {
      "asset_class": "cold_storage",
      "capacity_mw": null,
      "count": 75.0,
      "k": 0,
      "k_capacity_mw": 0,
      "k_count": 2,
      "count_range": "50-100",
      "count_range_min": 50.0,
      "count_range_max": 100.0,
      "capacity_mw_illustrative": false,
      "count_illustrative": true
    },
    {
      "asset_class": "ev_charger",
      "capacity_mw": null,
      "count": 200.0,
      "k": 0,
      "k_capacity_mw": 0,
      "k_count": 4,
      "count_range": null,
      "count_range_min": null,
      "count_range_max": null,
      "capacity_mw_illustrative": false,
      "count_illustrative": false
    },
    {
      "asset_class": "heat_network_thermal",
      "capacity_mw": null,
      "count": 300.0,
      "k": 0,
      "k_capacity_mw": 0,
      "k_count": 3,
      "count_range": "100-500",
      "count_range_min": 100.0,
      "count_range_max": 500.0,
      "capacity_mw_illustrative": false,
      "count_illustrative": true
    },
    {
      "asset_class": "heat_pump",
      "capacity_mw": null,
      "count": 7500.0,
      "k": 0,
      "k_capacity_mw": 0,
      "k_count": 1,
      "count_range": "5k-10k",
      "count_range_min": 5000.0,
      "count_range_max": 10000.0,
      "capacity_mw_illustrative": false,
      "count_illustrative": true
    },
    {
      "asset_class": "storage_heater",
      "capacity_mw": null,
      "count": null,
      "k": 0,
      "k_capacity_mw": 0,
      "k_count": 0,
      "count_range": null,
      "count_range_min": null,
      "count_range_max": null,
      "capacity_mw_illustrative": false,
      "count_illustrative": false
    },
    {
      "asset_class": "water_treatment",
      "capacity_mw": null,
      "count": null,
      "k": 0,
      "k_capacity_mw": 0,
      "k_count": 0,
      "count_range": null,
      "count_range_min": null,
      "count_range_max": null,
      "capacity_mw_illustrative": false,
      "count_illustrative": false
    }
  ],
  "service_breakdown": [],
  "narratives": {
    "headline": "This dashboard presents flexibility data from 15 contributing organisations for the study period Nov 2024-Feb 2025. Total available flexibility capacity is 16,300 MW.",
    "sector": "Sector breakdown data is limited in this release.",
    "delivery": "Delivery factor data is not yet available.",
    "coverage": "Data for this dashboard was provided by 15 organisations. Where fewer than 3 contributors exist for a metric, illustrative values are shown to protect commercial confidentiality."
  },
  "data_quality": {
    "total_submissions": 15,
    "valid_submissions": 15,
    "validation_rate": 1.0,
    "average_completeness": 1.212,
    "average_quality": 0.8399999999999999,
    "total_errors": 0,
    "total_warnings": 48,
    "common_errors": [],
    "common_warnings": [
      [
        "assets.market_share_pct: Low completeness (0.0%)",
        8
      ],
      [
        "assets.remarks: Low completeness (0.0%)",
        8
      ],
      [
        "assets.capacity_mw: Low completeness (0.0%)",
        8
      ],
      [
        "assets.portfolio_count: Low completeness (10.0%)",
        4
      ],
      [
        "assets.winter_active_count: Low completeness (10.0%)",
        4
      ]
    ]
  },
  "colors": {
    "primary": "#2E86AB",
    "secondary": "#A23B72",
    "tertiary": "#F18F01",
    "success": "#4CAF50",
    "warning": "#FF9800",
    "domestic": "#2E86AB",
    "ic": "#A23B72",
    "illustrative": "#FF9800"
  },
  "energy_metrics": {
    "total": {
      "delivered_gwh": 0.0,
      "delivered_gwh_illustrative": true,
      "delivered_range": "0",
      "delivered_range_min": 0.0,
      "delivered_range_max": 0.0
    },
    "explicit": {
      "delivered_gwh": 0.0,
      "delivered_gwh_illustrative": true,
      "delivered_range": "0",
      "delivered_range_min": 0.0,
      "delivered_range_max": 0.0
    },
    "implicit": {
      "delivered_gwh": 0.0,
      "delivered_gwh_illustrative": true,
      "delivered_range": "0",
      "delivered_range_min": 0.0,
      "delivered_range_max": 0.0
    }
  },
  "utilisation": null,
  "directional_breakdown": {
    "turn_up": {
      "capacity_mw": 0.0,
      "capacity_mw_illustrative": true,
      "capacity_range": "0 MW",
      "capacity_range_min": 0.0,
      "capacity_range_max": 0.0
    },
    "turn_down": {
      "capacity_mw": 0.0,
      "capacity_mw_illustrative": true,
      "capacity_range": "0 MW",
      "capacity_range_min": 0.0,
      "capacity_range_max": 0.0
    },
    "asymmetry_explanation": "Turn-down capacity is typically more widely available than turn-up, reflecting the prevalence of load reduction and load shifting compared to sustained load increases."
  },
  "flexibility_type_breakdown": {
    "explicit": {
      "capacity_mw": 16300,
      "capacity_mw_illustrative": false,
      "capacity_range": null,
      "capacity_range_min": null,
      "capacity_range_max": null
    },
    "implicit": {
      "capacity_mw": 0.0,
      "capacity_mw_illustrative": true,
      "capacity_range": "0 MW",
      "capacity_range_min": 0.0,
      "capacity_range_max": 0.0
    }
  },
  "asset_group_breakdown": [
    {
      "asset_group": "Other",
      "capacity_mw": 16300.0,
      "count": 314200,
      "k": 7,
      "k_capacity_mw": 7,
      "k_count": 7,
      "count_range": null,
      "count_range_min": null,
      "count_range_max": null,
      "capacity_mw_illustrative": false,
      "count_illustrative": false
    },
    {
      "asset_group": "Battery storage",
      "capacity_mw": null,
      "count": 300000,
      "k": 0,
      "k_capacity_mw": 0,
      "k_count": 6,
      "count_range": "100k-500k",
      "count_range_min": 100000.0,
      "count_range_max": 500000.0,
      "capacity_mw_illustrative": false,
      "count_illustrative": true
    },
    {
      "asset_group": "EV charging",
      "capacity_mw": null,
      "count": 200,
      "k": 0,
      "k_capacity_mw": 0,
      "k_count": 4,
      "count_range": null,
      "count_range_min": null,
      "count_range_max": null,
      "capacity_mw_illustrative": false,
      "count_illustrative": false
    },
    {
      "asset_group": "Heat",
      "capacity_mw": null,
      "count": 7500,
      "k": 0,
      "k_capacity_mw": 0,
      "k_count": 4,
      "count_range": "5k-10k",
      "count_range_min": 5000.0,
      "count_range_max": 10000.0,
      "capacity_mw_illustrative": false,
      "count_illustrative": true
    },
    {
      "asset_group": "I&C load/process",
      "capacity_mw": null,
      "count": 75,
      "k": 0,
      "k_capacity_mw": 0,
      "k_count": 2,
      "count_range": "50-100",
      "count_range_min": 50.0,
      "count_range_max": 100.0,
      "capacity_mw_illustrative": false,
      "count_illustrative": true
    }
  ],
  "sector_asset_breakdown": [
    {
      "sector": "unknown",
      "asset_class": "unknown",
      "capacity_mw": 16300.0,
      "count": 314200.0,
      "k": 7,
      "k_capacity_mw": 7,
      "k_count": 7,
      "count_range": null,
      "count_range_min": null,
      "count_range_max": null,
      "capacity_mw_illustrative": false,
      "count_illustrative": false
    },
    {
      "sector": "domestic",
      "asset_class": "battery_storage",
      "capacity_mw": null,
      "count": 300000.0,
      "k": 0,
      "k_capacity_mw": 0,
      "k_count": 3,
      "count_range": "100k-500k",
      "count_range_min": 100000.0,
      "count_range_max": 500000.0,
      "capacity_mw_illustrative": false,
      "count_illustrative": true
    },
    {
      "sector": "domestic",
      "asset_class": "ev_charger",
      "capacity_mw": null,
      "count": null,
      "k": 0,
      "k_capacity_mw": 0,
      "k_count": 0,
      "count_range": null,
      "count_range_min": null,
      "count_range_max": null,
      "capacity_mw_illustrative": false,
      "count_illustrative": false
    },
    {
      "sector": "domestic",
      "asset_class": "heat_pump",
      "capacity_mw": null,
      "count": null,
      "k": 0,
      "k_capacity_mw": 0,
      "k_count": 0,
      "count_range": null,
      "count_range_min": null,
      "count_range_max": null,
      "capacity_mw_illustrative": false,
      "count_illustrative": false
    },
    {
      "sector": "domestic",
      "asset_class": "storage_heater",
      "capacity_mw": null,
      "count": null,
      "k": 0,
      "k_capacity_mw": 0,
      "k_count": 0,
      "count_range": null,
      "count_range_min": null,
      "count_range_max": null,
      "capacity_mw_illustrative": false,
      "count_illustrative": false
    },
    {
      "sector": "ic",
      "asset_class": "battery_storage",
      "capacity_mw": null,
      "count": 120.0,
      "k": 0,
      "k_capacity_mw": 0,
      "k_count": 3,
      "count_range": null,
      "count_range_min": null,
      "count_range_max": null,
      "capacity_mw_illustrative": false,
      "count_illustrative": false
    },
    {
      "sector": "ic",
      "asset_class": "cold_storage",
      "capacity_mw": null,
      "count": 75.0,
      "k": 0,
      "k_capacity_mw": 0,
      "k_count": 2,
      "count_range": "50-100",
      "count_range_min": 50.0,
      "count_range_max": 100.0,
      "capacity_mw_illustrative": false,
      "count_illustrative": true
    },
    {
      "sector": "ic",
      "asset_class": "ev_charger",
      "capacity_mw": null,
      "count": 200.0,
      "k": 0,
      "k_capacity_mw": 0,
      "k_count": 4,
      "count_range": null,
      "count_range_min": null,
      "count_range_max": null,
      "capacity_mw_illustrative": false,
      "count_illustrative": false
    },
    {
      "sector": "ic",
      "asset_class": "heat_network_thermal",
      "capacity_mw": null,
      "count": 300.0,
      "k": 0,
      "k_capacity_mw": 0,
      "k_count": 3,
      "count_range": "100-500",
      "count_range_min": 100.0,
      "count_range_max": 500.0,
      "capacity_mw_illustrative": false,
      "count_illustrative": true
    },
    {
      "sector": "ic",
      "asset_class": "heat_pump",
      "capacity_mw": null,
      "count": 7500.0,
      "k": 0,
      "k_capacity_mw": 0,
      "k_count": 1,
      "count_range": "5k-10k",
      "count_range_min": 5000.0,
      "count_range_max": 10000.0,
      "capacity_mw_illustrative": false,
      "count_illustrative": true
    },
    {
      "sector": "ic",
      "asset_class": "water_treatment",
      "capacity_mw": null,
      "count": null,
      "k": 0,
      "k_capacity_mw": 0,
      "k_count": 0,
      "count_range": null,
      "count_range_min": null,
      "count_range_max": null,
      "capacity_mw_illustrative": false,
      "count_illustrative": false
    }
  ],
  "sector_asset_group_breakdown": [
    {
      "sector": "unknown",
      "asset_group": "Other",
      "capacity_mw": 16300.0,
      "count": 314200.0,
      "k": 7,
      "k_capacity_mw": 7,
      "k_count": 7,
      "count_range": null,
      "count_range_min": null,
      "count_range_max": null,
      "capacity_mw_illustrative": false,
      "count_illustrative": false
    },
    {
      "sector": "domestic",
      "asset_group": "Battery storage",
      "capacity_mw": null,
      "count": 300000.0,
      "k": 0,
      "k_capacity_mw": 0,
      "k_count": 3,
      "count_range": "100k-500k",
      "count_range_min": 100000.0,
      "count_range_max": 500000.0,
      "capacity_mw_illustrative": false,
      "count_illustrative": true
    },
    {
      "sector": "domestic",
      "asset_group": "EV charging",
      "capacity_mw": null,
      "count": null,
      "k": 0,
      "k_capacity_mw": 0,
      "k_count": 0,
      "count_range": null,
      "count_range_min": null,
      "count_range_max": null,
      "capacity_mw_illustrative": false,
      "count_illustrative": false
    },
    {
      "sector": "domestic",
      "asset_group": "Heat",
      "capacity_mw": null,
      "count": null,
      "k": 0,
      "k_capacity_mw": 0,
      "k_count": 0,
      "count_range": null,
      "count_range_min": null,
      "count_range_max": null,
      "capacity_mw_illustrative": false,
      "count_illustrative": false
    },
    {
      "sector": "ic",
      "asset_group": "Battery storage",
      "capacity_mw": null,
      "count": 120.0,
      "k": 0,
      "k_capacity_mw": 0,
      "k_count": 3,
      "count_range": null,
      "count_range_min": null,
      "count_range_max": null,
      "capacity_mw_illustrative": false,
      "count_illustrative": false
    },
    {
      "sector": "ic",
      "asset_group": "EV charging",
      "capacity_mw": null,
      "count": 200.0,
      "k": 0,
      "k_capacity_mw": 0,
      "k_count": 4,
      "count_range": null,
      "count_range_min": null,
      "count_range_max": null,
      "capacity_mw_illustrative": false,
      "count_illustrative": false
    },
    {
      "sector": "ic",
      "asset_group": "Heat",
      "capacity_mw": null,
      "count": 7500.0,
      "k": 0,
      "k_capacity_mw": 0,
      "k_count": 4,
      "count_range": "5k-10k",
      "count_range_min": 5000.0,
      "count_range_max": 10000.0,
      "capacity_mw_illustrative": false,
      "count_illustrative": true
    },
    {
      "sector": "ic",
      "asset_group": "I&C load/process",
      "capacity_mw": null,
      "count": 75.0,
      "k": 0,
      "k_capacity_mw": 0,
      "k_count": 2,
      "count_range": "50-100",
      "count_range_min": 50.0,
      "count_range_max": 100.0,
      "capacity_mw_illustrative": false,
      "count_illustrative": true
    }
  ],
  "coverage": {
    "contributors_total": 15,
    "k_threshold": 3,
    "capacity_mw_contributors": 7,
    "delivered_mw_contributors": 0,
    "explicit_energy_contributors": 0,
    "implicit_energy_contributors": 0,
    "implicit_capacity_contributors": 0,
    "portfolio_count_contributors": 15
  },
  "benchmarks": {
    "dy": "2024/25",
    "unit": "kW",
    "non_additivity_notice": "Capacity Market figures are used as an external benchmark only and are not added to dashboard totals.",
    "methods_summary": "Capacity Market values represent de-rated capacity awards for CMUs in Delivery Year 2024/25 (union of T-4 and T-1 auctions, summed where the same CMU appears in both).\nDashboard contributor figures reflect the project study period Nov 2024–Feb 2025 and follow the dashboard working capacity definition.\nExpect differences due to (i) definitions (de-rated MW vs working capacity), (ii) period coverage (Delivery Year vs Nov–Feb), (iii) overlaps across services (double counting not inferred), and (iv) contributor coverage (domestic under-represented in CM).\n",
    "sources": [
      {
        "name": "EMR Capacity Auction Results (index)",
        "url": "https://www.emrdbcapacityauction.com/"
      },
      {
        "name": "T-1 Auction 2023 (DY 2024/25): Final Results Report (v1.0)",
        "url": "https://www.emrdeliverybody.com/Capacity%20Markets%20Document%20Library/T-1%20DY%202024-25%20Final%20Results%20Report%20v1.0.pdf"
      },
      {
        "name": "T-4 Auction 2020 (DY 2024/25): Final Report",
        "url": "https://www.emrdeliverybody.com/Capacity%20Markets%20Document%20Library/Capacity%20Market%20Auction%20T4%20DY2024-25%20Final%20Report.pdf"
      },
      {
        "name": "NESO Capacity Market portal",
        "url": "https://www.neso.energy/what-we-do/energy-markets/electricity-market-reform-emr-delivery-body/capacity-market-portal"
      },
      {
        "name": "Ofgem: Decision on the Delivery Body review of the Relevant Balancing Services Guidelines (2024)",
        "url": "https://www.ofgem.gov.uk/sites/default/files/2024-03/Decision%20on%20the%20Delivery%20Body%27s%20review%20of%20the%20Relevant%20Balancing%20Services%20Guidelines%202024.pdf"
      }
    ],
    "cm_benchmark_by_asset": [
      {
        "asset_class": "Battery",
        "cm_benchmark_kw": 790.0
      },
      {
        "asset_class": "I&C load",
        "cm_benchmark_kw": 2378879.0
      }
    ],
    "comparison": [
      {
        "asset_class": "Battery",
        "contributors_kw": 0.0,
        "contributors_k": 0,
        "contributors_illustrative": false,
        "contributors_range": null,
        "contributors_range_min_kw": null,
        "contributors_range_max_kw": null,
        "cm_benchmark_kw": 790.0,
        "variance_kw": -790.0,
        "variance_pct": -1.0
      },
      {
        "asset_class": "EV",
        "contributors_kw": 0.0,
        "contributors_k": 0,
        "contributors_illustrative": false,
        "contributors_range": null,
        "contributors_range_min_kw": null,
        "contributors_range_max_kw": null,
        "cm_benchmark_kw": 0.0,
        "variance_kw": 0.0,
        "variance_pct": null
      },
      {
        "asset_class": "Heat",
        "contributors_kw": 0.0,
        "contributors_k": 0,
        "contributors_illustrative": false,
        "contributors_range": null,
        "contributors_range_min_kw": null,
        "contributors_range_max_kw": null,
        "cm_benchmark_kw": 0.0,
        "variance_kw": 0.0,
        "variance_pct": null
      },
      {
        "asset_class": "I&C load",
        "contributors_kw": 16300000.0,
        "contributors_k": 7,
        "contributors_illustrative": false,
        "contributors_range": null,
        "contributors_range_min_kw": null,
        "contributors_range_max_kw": null,
        "cm_benchmark_kw": 2378879.0,
        "variance_kw": 13921121.0,
        "variance_pct": 5.8519668298
      }
    ]
  }
};
